### ISSUE TITLE
Methods without parameters require a space character to run correctly

### ISSUE THREAD

**Issue by mtardal** [sgbasaraner/yeelight-cli#2]
Methods like "toggle", "set_default" which don't have any parameters, require a space character at the end of the command to work, otherwise the bulb returns "invalid command" message.

Thanks for this sick lil wrapper by the way. I had some ideas about Yeelight but was too lazy to start as the existing sources were mostly in Chinese, this will be an useful base for me to build on top of.

**Comment by mtardal** [comment]
I looked at the source code and I think the source stems from parsing of the parameters when there isn't any parameters. I can fix it if you want.

**Comment by sgbasaraner** [comment]
Thank you for the notification. Yes, I think your assessment is correct. I'm waiting for a pull request.
