### ISSUE TITLE
Yeelight-cli & Home Assistant (bulb closes connection)

### ISSUE THREAD

**Issue by Hukuma1** [sgbasaraner/yeelight-cli#4]
Can I simply reference this: https://github.com/home-assistant/core/issues/35202

Bulb seems to close the connection and not take any commands. Would love to debug this in case it's something we can potentially fix without waiting for some magic firmware fix.

**Comment by sgbasaraner** [comment]
I am not familiar with home-assistant, I tested yeelight-cli with my bulb and it seems to work OK. I did have to reset the bulb before being able to connect though (haven't used it in a while). Can you give some pointers for recreating the issue with yeelight-cli?

**Comment by Hukuma1** [comment]
My apologies. It seems HA uses a different library for controlling Yeelight. D: Closing this non-issue here. Thanks for the replies!
